<?php
// @todo: parametrise footer data
?>
<div class="container">
    <div class="row">
        <div class="logo col-lg-12 col-sm-12 footer-pt-10">
            <a href="<?php echo $block->getUrl('/'); ?>">
                <img src="<?php echo $block->getViewFileUrl('images/vatogo-logo/vatogo-logo-grey.svg'); ?>">
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="footer_log_text">
                <?php echo __('Develop by Farid') ?>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="footer_text">
                <?php echo __('Privacy Policy / Terms and Conditions') ?>
            </div>
        </div>
    </div>
</div>
